# Hardflow is free and GPLv3. If it saves you a license fee, consider supporting
# development. Uncomment and fill in whichever platforms you use.

# github: [ugulay]
# ko_fi: your_kofi_handle
# buy_me_a_coffee: your_bmac_handle
# custom: ["https://example.com/donate"]
